language: python
python:
  - "2.7"

env:
  global:
    # for $TENDENCI_TRANSIFEX_PASSWORD
    secure: "odfSCDi6UKkIKu9Vi5Rx3fXi0CgIZa3y5w1jcsVluaLijXqLPMHj215FzV1Y5jF7tI/GbnHrLy3LhRfPPRlpaHvE3zDe5ZZYLKfOMmPtYEYPghFFVoiY7138jNssqxwF5kV85pxEQ49nDzK8fqHnfgqJEn3pJkdZlOKB3KQiskw="

# command to install dependencies
install:
  - pip install "Django>=1.8,<1.9"

# TODO: command to run tests
# for now, run command to push source and translation files to Transifex
script: ./transifex.sh
